# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 01:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.FloatField()),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=50)),
                ('timesBought', models.IntegerField(default=0)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.FloatField()),
                ('date', models.DateField()),
                ('ostentacaoCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('CEP', models.IntegerField(blank=True)),
                ('number', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('complement', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User'),
        ),
        migrations.AddField(
            model_name='purchasedproducts',
            name='idPurchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.PurchaseHistory'),
        ),
    ]
