# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('timesBought', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.FloatField()),
                ('date', models.DateField()),
                ('ostentacaoCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('CEP', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='products',
            field=models.ManyToManyField(to='API.Product'),
        ),
    ]
