# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170919_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='products',
            field=models.ManyToManyField(to='API.Product'),
        ),
    ]
